---
name: Unit tests

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unit.yml'
      - 'plugins/**'
      - 'tests/unit/**'

jobs:
  unit-test:
    name: Unit test Ansible ${{ matrix.ansible }} Py${{ matrix.python }}
    if: ${{ github.event.label.name == 'automation' || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/vultr/cloud
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.11
          - stable-2.13
        python:
          - 2.7
          - 3.6
          - 3.8
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/vultr/cloud

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible-base (${{ matrix.ansible }})
        run: |
          python -m pip install --upgrade pip
          pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Build and install collection
        run: |
          ansible-galaxy collection build .
          ansible-galaxy collection install *.gz

      - name: Run the tests
        run: >-
          ansible-test
          units
          --docker
          -v
          --color
          --continue-on-error
          --diff
          --python ${{ matrix.python }}
          --coverage

      - name: Generate coverage report
        run: >-
          ansible-test
          coverage xml
          -v
          --requirements
          --group-by command
          --group-by version
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
